language: ruby 
script: ./utils/run-tests.sh
install: sudo gem install rspec 
rvm:
  - 1.8
  - 1.8.6
  - 1.8.7
  - 1.9
  - 1.9.1
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - ruby-head
  - jruby-head
  - ree
